# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 69428aa76bb4711be99b8b05924a47d5fd724d40891f6be97e6d0be0233285984cffa8fa7e845c16463ef9bbbc3faff30232971af09d68e861359e2bf8732dfc

test:
  secret_key_base: 5523c1c62a15843f7b9deb5f0317a8ebb1bf5cf13e026d350a7d69ff940981a247f060b91080212280cc0df337dbfad127c095e7ac44e04b460309b1a8c398fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
